csv_file: "Data/Ext_Ant_Scan/scan_pose_list_ee.csv"
obstacles_file: "Data/Ext_Ant_Scan/obstacles.xml"
urdf_file: "/Users/joris/Uni/MA/Code/PathPlanner_US_wip/res/scenario_1/panda_US.urdf"
output_file: "debug_results.json"

stomp:
  temperature: 25.0
  learning_rate: 0.4
  max_iterations: 120
  N: 100
  num_noisy_trajectories: 32
  num_best_samples: 12
  obstacle_cost_weight: 2.5
  constraint_cost_weight: 2.0

evaluation:
  trajectory_pairs: 10
