# Optimal STOMP parameters found by Optuna optimization
# Trial 12 - Composite Score: 0.1973
csv_file: "/Users/joris/Uni/MA/Code/PathPlanner_US_wip/apps/ParameterTuning/Data/Ext_Ant_Scan/scan_pose_list_ee.csv"
obstacles_file: "/Users/joris/Uni/MA/Code/PathPlanner_US_wip/apps/ParameterTuning/Data/Ext_Ant_Scan/obstacles.xml"
urdf_file: "/Users/joris/Uni/MA/robot_definition/panda_US.urdf"
output_file: "optimal_results.json"

stomp:
  temperature: 7.713967922616584
  learning_rate: 0.5835530118328666
  max_iterations: 50
  N: 50
  num_noisy_trajectories: 4
  num_best_samples: 8
  obstacle_cost_weight: 1.434745952388944
  constraint_cost_weight: 4.942419046519428
  joint_std_devs: [0.05571445200484644, 0.10750637636454857, 0.0634973618331383, 0.0269392655597457, 0.0220168342793176, 0.09367926093361557, 0.022376127532167764]

evaluation:
  trajectory_pairs: 100  # Comprehensive evaluation with many pose pairs for long optimization run

# Performance metrics:
# Success Rate: 1.0
# Avg Planning Time: 205.536145875ms
# Composite Score: 0.1973
