algorithm: STOMP
parameters:
  num_noisy_trajectories: 50
  num_best_samples: 20
  max_iterations: 100
  learning_rate: 0.3
  temperature: 15.0
  dt: 0.05
  velocity_limit: 1.5
  acceleration_limit: 0.4

scenarios:
  - name: test_scenario_1
    description: Real ultrasound scanning scenario
    difficulty: 1
    start_config: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    environment: scenario_1
    urdf: panda_US

evaluation_settings:
  num_runs_per_scenario: 3
  timeout_seconds: 30
  output_trajectories: false

resources:
  obstacles_file: /Users/joris/Uni/MA/Code/PathPlanner_US_wip/res/scenario_1/obstacles.xml
  urdf_file: /Users/joris/Uni/MA/Code/PathPlanner_US_wip/res/scenario_1/panda_US.urdf
  poses_file: /Users/joris/Uni/MA/Code/PathPlanner_US_wip/res/scenario_1/scan_poses.csv
