csv_file: Data/Ext_Ant_Scan/scan_pose_list_ee.csv
temperature: 15.0
learningRate: 0.3
maxIterations: 80
dt: 0.05
numNoisyTrajectories: 20
numBestSamples: 5
evaluation:
  trajectory_pairs: 5
output_file: test_results.json
