csv_file: "/Users/joris/Uni/MA/Code/PathPlanner_US_wip/res/scenario_1/scan_poses.csv"
obstacles_file: "/Users/joris/Uni/MA/Code/PathPlanner_US_wip/res/scenario_1/obstacles.xml"
urdf_file: "/Users/joris/Uni/MA/Code/PathPlanner_US_wip/res/scenario_1/panda_US.urdf"
output_file: "test_small_results.json"

stomp:
  temperature: 15.0
  learning_rate: 0.3
  max_iterations: 50
  dt: 0.05
  num_noisy_trajectories: 8
  num_best_samples: 4

evaluation:
  trajectory_pairs: 2
