# Optimal STOMP parameters found by Optuna optimization
# Trial 29 - Composite Score: 2.1201
csv_file: "/Users/joris/Uni/MA/Code/PathPlanner_US_wip/apps/ParameterTuning/Data/Ext_Ant_Scan/scan_pose_list_ee.csv"
obstacles_file: "/Users/joris/Uni/MA/Code/PathPlanner_US_wip/apps/ParameterTuning/Data/Ext_Ant_Scan/obstacles.xml"
urdf_file: "/Users/joris/Uni/MA/Code/PathPlanner_US_wip/res/scenario_1/panda_US.urdf"
output_file: "optimal_results.json"

stomp:
  temperature: 16.98095545703236
  learning_rate: 0.5215232058642698
  max_iterations: 70
  N: 70
  num_noisy_trajectories: 28
  num_best_samples: 10
  obstacle_cost_weight: 3.165084464152532
  constraint_cost_weight: 2.498454879702484

evaluation:
  trajectory_pairs: 20  # Use more pairs for final validation

# Performance metrics:
# Success Rate: 1.0
# Avg Planning Time: 4858.993307375ms
# Composite Score: 2.1201
