# Optimized STOMP parameters with heavy failure penalties
# Best trial: 9
# Best composite score: 4.200000
# Total evaluations: 600

csv_file: /Users/joris/Uni/MA/Code/PathPlanner_US_wip/apps/ParameterTuning/Data/Ext_Ant_Scan/scan_pose_list_ee.csv
evaluation:
  trajectory_pairs: 30
obstacles_file: /Users/joris/Uni/MA/Code/PathPlanner_US_wip/apps/ParameterTuning/Data/Ext_Ant_Scan/obstacles.xml
output_file: trial_results.json
stomp:
  N: 50
  constraint_cost_weight: 3.0875877758611727
  joint_std_devs:
  - 0.1097511058802007
  - 0.10366719553965768
  - 0.05580679647895116
  - 0.1499988646522685
  - 0.0612900208937102
  - 0.014783827172642509
  - 0.03620810490184459
  learning_rate: 0.9979982774302885
  max_iterations: 50
  num_best_samples: 3
  num_noisy_trajectories: 12
  obstacle_cost_weight: 3.5304763460000332
  temperature: 19.289304764744003
urdf_file: /Users/joris/Uni/MA/robot_definition/panda_US.urdf
