# STOMP Success Rate Optimization Config
numNoisyTrajectories: 15
numBestSamples: 10
maxIterations: 200
N: 40
learningRate: 0.7
temperature: 12.0

# Cost weights optimized for success rate
obstacleCostWeight: 8.0
smoothnessCostWeight: 0.3
velocityCostWeight: 0.1
accelerationCostWeight: 0.1
goalCostWeight: 5.0
collisionPenaltyWeight: 80.0
prioritizeSuccessRate: true
constraintRelaxationFactor: 1.8

# Early stopping for efficiency
enableEarlyStopping: true
earlyStoppingPatience: 1
maxComputeTimeMs: 4000.0

# Optimized joint noise
jointStdDevs: [0.149691, 0.0132654, 0.0450644, 0.103875, 0.0647333, 0.131444, 0.113796]
