# Success Rate Optimized STOMP Configuration
# Focus on finding ANY collision-free solution

csv_file: /Users/joris/Uni/MA/Code/PathPlanner_US_wip/apps/ParameterTuning/Data/Ext_Ant_Scan/scan_pose_list_ee.csv
evaluation:
  trajectory_pairs: 50
obstacles_file: /Users/joris/Uni/MA/Code/PathPlanner_US_wip/apps/ParameterTuning/Data/Ext_Ant_Scan/obstacles.xml
output_file: success_rate_results.json
stomp:
  N: 40                                  # Fewer points for faster computation
  constraint_cost_weight: 0.1            # Very low weight to allow constraint violations
  joint_std_devs:
  - 0.14969074521794967                  # Keep optimized noise values
  - 0.013265385613107944
  - 0.045064390929169765
  - 0.10387464719708213
  - 0.064733344435142
  - 0.13144377546895014
  - 0.11379621126089833
  learning_rate: 0.7                     # Lower learning rate for stability
  max_iterations: 200                    # More iterations to find solutions
  num_best_samples: 10                   # Keep more good samples
  num_noisy_trajectories: 15             # More exploration
  obstacle_cost_weight: 8.0              # High weight for collision avoidance
  temperature: 12.0                      # Higher temperature for exploration
urdf_file: /Users/joris/Uni/MA/robot_definition/panda_US.urdf
