# Extreme constraint weight test - should now be manageable with improved calculation
csv_file: /Users/joris/Uni/MA/Code/PathPlanner_US_wip/apps/ParameterTuning/Data/Ext_Ant_Scan/scan_pose_list_ee.csv
evaluation:
  trajectory_pairs: 3
obstacles_file: /Users/joris/Uni/MA/Code/PathPlanner_US_wip/apps/ParameterTuning/Data/Ext_Ant_Scan/obstacles.xml
output_file: extreme_constraint_test_results.json
stomp:
  N: 80  # More waypoints to test cost accumulation
  constraint_cost_weight: 15.0  # Extremely high weight
  joint_std_devs:
  - 0.2
  - 0.1
  - 0.1
  - 0.2
  - 0.15
  - 0.2
  - 0.15
  learning_rate: 0.8
  max_iterations: 30
  num_best_samples: 5
  num_noisy_trajectories: 10
  obstacle_cost_weight: 2.0
  temperature: 8.0
urdf_file: /Users/joris/Uni/MA/robot_definition/panda_US.urdf
