# High Success Rate STOMP Configuration
# Prioritizes finding ANY collision-free solution over quality

csv_file: /Users/joris/Uni/MA/Code/PathPlanner_US_wip/apps/ParameterTuning/Data/Ext_Ant_Scan/scan_pose_list_ee.csv
evaluation:
  trajectory_pairs: 50
obstacles_file: /Users/joris/Uni/MA/Code/PathPlanner_US_wip/apps/ParameterTuning/Data/Ext_Ant_Scan/obstacles.xml
output_file: high_success_results.json
stomp:
  N: 40                                  # Fewer points for faster convergence
  constraint_cost_weight: 0.5            # Much lower constraint penalty
  joint_std_devs:                        # Keep optimized noise values
  - 0.14969074521794967                  
  - 0.013265385613107944
  - 0.045064390929169765
  - 0.10387464719708213
  - 0.064733344435142
  - 0.13144377546895014
  - 0.11379621126089833
  learning_rate: 0.6                     # Lower learning rate for stability
  max_iterations: 150                    # More iterations to find solutions
  num_best_samples: 12                   # Keep more good samples
  num_noisy_trajectories: 20             # Much more exploration
  obstacle_cost_weight: 5.0              # Higher collision avoidance
  temperature: 15.0                      # Higher temperature for exploration
urdf_file: /Users/joris/Uni/MA/robot_definition/panda_US.urdf
