# Improved constraint cost test config
csv_file: /Users/joris/Uni/MA/Code/PathPlanner_US_wip/apps/ParameterTuning/Data/Ext_Ant_Scan/scan_pose_list_ee.csv
evaluation:
  trajectory_pairs: 2  # Test two pairs
obstacles_file: /Users/joris/Uni/MA/Code/PathPlanner_US_wip/apps/ParameterTuning/Data/Ext_Ant_Scan/obstacles.xml
output_file: improved_cost_results.json
stomp:
  N: 50
  constraint_cost_weight: 2.0  # Reasonable weight (not 5.0)
  joint_std_devs:
  - 0.14969074521794967
  - 0.013265385613107944
  - 0.045064390929169765
  - 0.10387464719708213
  - 0.064733344435142
  - 0.13144377546895014
  - 0.11379621126089833
  learning_rate: 0.9500184463375958
  max_iterations: 50
  num_best_samples: 8
  num_noisy_trajectories: 11
  obstacle_cost_weight: 2.95
  temperature: 10.455122306225036
urdf_file: /Users/joris/Uni/MA/robot_definition/panda_US.urdf
