# Test configuration with heavy penalties for STOMP failures
csv_file: "/Users/joris/Uni/MA/Code/PathPlanner_US_wip/apps/ParameterTuning/Data/Ext_Ant_Scan/scan_pose_list_ee.csv"
obstacles_file: "/Users/joris/Uni/MA/Code/PathPlanner_US_wip/apps/ParameterTuning/Data/Ext_Ant_Scan/obstacles.xml"
urdf_file: "/nonexistent/path/to/test/failure/penalties.urdf"  # Intentionally wrong path to test failure penalties
output_file: "heavy_penalty_test_results.json"

stomp:
  temperature: 15.0
  learning_rate: 0.3
  max_iterations: 50
  N: 50
  num_noisy_trajectories: 8
  num_best_samples: 4
  obstacle_cost_weight: 1.0
  constraint_cost_weight: 1.0
  joint_std_devs: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

evaluation:
  trajectory_pairs: 5  # Small number for quick test
