# Trajectory Planning Evaluation Configuration
# This file defines parameter ranges for comprehensive algorithm evaluation

evaluation:
  # Test scenarios
  test_poses: 10                    # Use middle 10 poses from dataset
  trials_per_config: 5              # Number of trials per configuration
  output_directory: "results"
  
  # Default start joint configuration (safe starting position)
  start_joints: [0.0, -0.5, 0.0, -1.5, 0.0, 1.0, 0.0]

# STOMP Algorithm Parameter Sweep
stomp_parameters:
  max_iterations: [50, 100, 200]
  num_noisy_trajectories: [5, 10, 20]
  num_best_samples: [3, 4, 6]
  learning_rate: [0.05, 0.1, 0.2]
  temperature: [5.0, 10.0, 15.0]
  dt: [0.05, 0.1, 0.15]
  
  # Joint standard deviations (uniform for all joints)
  joint_std_dev: [0.05, 0.1, 0.15]

# Hauser Algorithm Parameter Sweep
hauser_parameters:
  max_iterations: [500, 1000, 2000]
  step_size: [0.05, 0.1, 0.2]
  goal_bias: [0.05, 0.1, 0.15]
  connection_radius: [0.2, 0.3, 0.4]  # For RRT* variants
  
  # Algorithm variants to test
  variants:
    - RRT                    # Basic RRT
    - RRT_STAR              # RRT* with rewiring
    - INFORMED_RRT_STAR     # Informed RRT* with heuristic sampling
    - BI_RRT                # Bidirectional RRT

# Evaluation metrics to analyze
metrics:
  - planning_time_ms        # Time to plan trajectory
  - execution_time_ms       # Estimated execution time
  - success_rate           # Success percentage
  - iterations_used        # Number of iterations consumed
  - trajectory_length      # Number of waypoints
  - path_quality          # Overall path quality score
  - joint_smoothness      # Joint motion smoothness
  - collision_clearance   # Minimum clearance from obstacles
  
# Visualization settings
visualization:
  pdf_dpi: 300
  figure_size: [16, 12]
  color_scheme: "professional"
  include_statistical_tests: true
  
# Quick evaluation mode (for testing)
quick_mode:
  test_poses: 3
  trials_per_config: 2
  stomp_configs: 3          # Limit STOMP configurations
  hauser_configs: 3         # Limit Hauser configurations
